# Demyx
# https://demyx.sh
#
# This docker-compose.yml is designed for VPS use with SSL/TLS first.
# Traefik requires no additional configurations and is ready to go.
# Be sure to change all the domain.tld domains and credentials before running docker-compose up -d.
#
networks:
  demyx:
    name: demyx
  demyx_socket:
    name: demyx_socket
services:
  demyx_bs:
    container_name: demyx_bs
    depends_on:
      - demyx_db
    environment:
      - DEMYX=/demyx
      - DEMYX_CONFIG=/etc/demyx
      - DEMYX_DOMAIN_MATCH=domain.tld
      - DEMYX_DOMAIN_RETURN=domain.tld
      - DEMYX_DOMAIN_SOCKET=domain.tld
      - DEMYX_FILES="/demyx/wp-content/themes/**/*" # Change this to whatever path you want browsersync to watch
      - DEMYX_LOG=/var/log/demyx
      - DEMYX_PATH=/demyx
      - DEMYX_PORT=3000
      - DEMYX_PREFIX=/bs
      - DEMYX_PROXY=demyx_nx # must match nginx service name
      - TZ=America/Los_Angeles
    image: demyx/browsersync
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.demyx-bs-prefix.stripprefix.prefixes=/demyx/bs/"
      - "traefik.http.middlewares.demyx-bs-socket-prefix.stripprefix.prefixes=/demyx/bs/browser-sync/socket.io/"
      - "traefik.http.routers.demyx-bs-socket.entrypoints=https"
      - "traefik.http.routers.demyx-bs-socket.priority=99"
      - "traefik.http.routers.demyx-bs-socket.rule=(Host(`domain.tld`) && PathPrefix(`/browser-sync/socket.io/`))"
      - "traefik.http.routers.demyx-bs-socket.service=demyx-bs-socket"
      - "traefik.http.routers.demyx-bs-socket.tls.certresolver=demyx"
      - "traefik.http.routers.demyx-bs.entrypoints=https"
      - "traefik.http.routers.demyx-bs.middlewares=demyx-bs-prefix"
      - "traefik.http.routers.demyx-bs.priority=99"
      - "traefik.http.routers.demyx-bs.rule=(Host(`domain.tld`) && PathPrefix(`/demyx/bs/`))" # Browsersync https://domain.tld/demyx/bs/
      - "traefik.http.routers.demyx-bs.service=demyx-bs"
      - "traefik.http.routers.demyx-bs.tls.certresolver=demyx"
      - "traefik.http.services.demyx-bs-socket.loadbalancer.server.port=3000"
      - "traefik.http.services.demyx-bs.loadbalancer.server.port=3000"
    networks:
      - demyx
    restart: unless-stopped
    volumes:
      - demyx_wp:/demyx
  demyx_db:
    container_name: demyx_db
    depends_on:
      - demyx_traefik
    environment:
      - DEMYX=/demyx
      - DEMYX_CONFIG=/etc/demyx
      - DEMYX_DATABASE=demyx
      - DEMYX_DOMAIN=domain.tld
      - DEMYX_INNODB_BUFFER_POOL_SIZE=128M
      - DEMYX_INNODB_LOG_BUFFER_SIZE=64M
      - DEMYX_LOG=/var/log/demyx
      - DEMYX_PASSWORD=demyx
      - DEMYX_ROOT_PASSWORD=demyx_root  # Mandatory
      - DEMYX_USERNAME=demyx
      - TZ=America/Los_Angeles
    image: demyx/mariadb
    networks:
      - demyx
    restart: unless-stopped
    volumes:
      - demyx_custom:/etc/demyx/custom
      - demyx_db:/demyx
      - demyx_log:/var/log/demyx
  demyx_nx:
    container_name: demyx_nx
    depends_on:
      - demyx_wp
    environment:
      - DEMYX=/demyx
      - DEMYX_BASIC_AUTH=false
      - DEMYX_BASIC_AUTH_PASSWORD=demyx
      - DEMYX_BASIC_AUTH_USERNAME=demyx
      - DEMYX_BASIC_AUTH_WP=false
      - DEMYX_BEDROCK=false
      - DEMYX_CACHE=false
      - DEMYX_CACHE_INACTIVE=60m
      - DEMYX_CACHE_TYPE=default
      - DEMYX_CONFIG=/etc/demyx
      - DEMYX_DOMAIN=domain.tld
      - DEMYX_LOG=/var/log/demyx
      - DEMYX_RATE_LIMIT=false
      - DEMYX_UPLOAD_LIMIT=256M
      - DEMYX_WHITELIST=false
      - DEMYX_WHITELIST_IP=false
      - DEMYX_WORDPRESS=true
      - DEMYX_WORDPRESS_CONTAINER=demyx_wp
      - DEMYX_XMLRPC=false
      - TZ=America/Los_Angeles
    image: demyx/nginx
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.demyx-nx-redirect.redirectregex.permanent=true"
      - "traefik.http.middlewares.demyx-nx-redirect.redirectregex.regex=^https?:\/\/(?:www\\.)?(.+)"
      - "traefik.http.middlewares.demyx-nx-redirect.redirectregex.replacement=https://$${1}"
      - "traefik.http.routers.demyx-nx-http.entrypoints=http"
      - "traefik.http.routers.demyx-nx-http.middlewares=demyx-nx-redirect"
      - "traefik.http.routers.demyx-nx-http.rule=Host(`domain.tld`) || Host(`www.domain.tld`)"
      - "traefik.http.routers.demyx-nx-http.service=demyx-nx-http-port"
      - "traefik.http.routers.demyx-nx-https.entrypoints=https"
      - "traefik.http.routers.demyx-nx-https.rule=Host(`domain.tld`) || Host(`www.domain.tld`)" # WordPress https://domain.tld
      - "traefik.http.routers.demyx-nx-https.service=demyx-nx-https-port"
      - "traefik.http.routers.demyx-nx-https.tls.certresolver=demyx"
      - "traefik.http.services.demyx-nx-http-port.loadbalancer.server.port=80"
      - "traefik.http.services.demyx-nx-https-port.loadbalancer.server.port=80"
    networks:
      - demyx
    restart: unless-stopped
    volumes:
      - demyx_custom:/etc/demyx/custom
      - demyx_log:/var/log/demyx
      - demyx_wp:/demyx
  demyx_pma:
    container_name: demyx_pma
    environment:
      - MYSQL_ROOT_PASSWORD=demyx_root
      - PMA_ABSOLUTE_URI=https://domain.tld/demyx/pma/
      - PMA_HOST=demyx_db
    image: phpmyadmin/phpmyadmin
    networks:
      - demyx
    restart: unless-stopped
    depends_on:
      - demyx_wp
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.demyx-pma-prefix.stripprefix.prefixes=/demyx/pma/"
      - "traefik.http.routers.demyx-pma.entrypoints=https"
      - "traefik.http.routers.demyx-pma.middlewares=demyx-pma-prefix"
      - "traefik.http.routers.demyx-pma.priority=99"
      - "traefik.http.routers.demyx-pma.rule=Host(`domain.tld`) && PathPrefix(`/demyx/pma/`)" # phpMyAdmin https://domain.tld/demyx/pma/
      - "traefik.http.routers.demyx-pma.service=demyx-pma-port"
      - "traefik.http.routers.demyx-pma.tls.certresolver=demyx"
      - "traefik.http.services.demyx-pma-port.loadbalancer.server.port=80"
  demyx_socket:
    container_name: demyx_socket
    environment:
      - CONTAINERS=1
    image: demyx/docker-socket-proxy
    networks:
      - demyx_socket
    # Uncomment below if your host OS is CentOS/RHEL/Fedora
    #privileged: true
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  demyx_traefik:
    container_name: demyx_traefik
    depends_on:
      - demyx_socket
    environment:
      # Uncomment below for Cloudflare DNS challenge
      #- CF_API_EMAIL=info@domain.tld
      #- CF_API_KEY=123456
      - DEMYX_ACME_EMAIL=info@domain.tld
      - DEMYX_TRAEFIK_LOG=INFO
      - TRAEFIK_PROVIDERS_DOCKER_ENDPOINT=tcp://demyx_socket:2375
    image: demyx/traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.demyx-traefik-auth.basicauth.users=demyx:$$apr1$$L91z3CIR$$m/BKZcnQGBP.Uo2cJm8I0/" # Basic auth password: demyx
      - "traefik.http.middlewares.demyx-traefik-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.demyx-traefik-http.entrypoints=http"
      - "traefik.http.routers.demyx-traefik-http.middlewares=demyx-traefik-redirect"
      - "traefik.http.routers.demyx-traefik-http.rule=Host(`traefik.domain.tld`)"
      - "traefik.http.routers.demyx-traefik-http.service=demyx-traefik-http-port"
      - "traefik.http.routers.demyx-traefik-https.entrypoints=https"
      - "traefik.http.routers.demyx-traefik-https.middlewares=demyx-traefik-auth"
      - "traefik.http.routers.demyx-traefik-https.rule=Host(`traefik.domain.tld`)" # Traefik dashboard https://traefik.domain.tld
      - "traefik.http.routers.demyx-traefik-https.service=api@internal"
      - "traefik.http.routers.demyx-traefik-https.service=demyx-traefik-https-port"
      - "traefik.http.routers.demyx-traefik-https.tls.certresolver=demyx"
      - "traefik.http.services.demyx-traefik-http-port.loadbalancer.server.port=8080"
      - "traefik.http.services.demyx-traefik-https-port.loadbalancer.server.port=8080"
    networks:
      - demyx
      - demyx_socket
    ports:
      - 80:80/tcp
      - 80:80/udp
      - 443:443/tcp
      - 443:443/udp
    restart: unless-stopped
    volumes:
      - demyx_log:/var/log/demyx
      - demyx_traefik:/demyx
  demyx_wp:
    container_name: demyx_wp
    depends_on:
      - demyx_db
    environment:
      - DEMYX=/demyx
      - DEMYX_BEDROCK=false
      - DEMYX_CODE_AUTH=password
      - DEMYX_CODE_BIND_ADDR=0.0.0.0:8080
      - DEMYX_CODE_CONFIG=/home/demyx/.config/code-server
      - DEMYX_CODE_PASSWORD=demyx
      - DEMYX_CONFIG=/etc/demyx
      - DEMYX_CRON=true
      - DEMYX_CRON_LOGROTATE_INTERVAL="0 0 * * *"
      - DEMYX_CRON_WP_INTERVAL="*/5 * * * *"
      - DEMYX_DB_HOST=demyx_db
      - DEMYX_DB_NAME=demyx
      - DEMYX_DB_PASSWORD=demyx
      - DEMYX_DB_USERNAME=demyx
      - DEMYX_DOMAIN=domain.tld
      - DEMYX_EMERGENCY_RESTART_INTERVAL=1m
      - DEMYX_EMERGENCY_RESTART_THRESHOLD=5
      - DEMYX_LOG=/var/log/demyx
      - DEMYX_LOGROTATE=daily
      - DEMYX_LOGROTATE_INTERVAL=7
      - DEMYX_LOGROTATE_SIZE=10M
      - DEMYX_MAX_EXECUTION_TIME=300
      - DEMYX_MEMORY=256M
      - DEMYX_OPCACHE=true
      - DEMYX_OPCACHE_ENABLE=1
      - DEMYX_OPCACHE_ENABLE_CLI=1
      - DEMYX_PHP=8.2
      - DEMYX_PM_AVERAGE=100000
      - DEMYX_PM_MAX_REQUESTS=5000
      - DEMYX_PROCESS_CONTROL_TIMEOUT=10s
      - DEMYX_PROTO=http
      - DEMYX_UPLOAD_LIMIT=256M
      - DEMYX_WP_CONFIG=/demyx/wp-config.php
      - DEMYX_WP_EMAIL=info@domain.tld
      - DEMYX_WP_PASSWORD=demyx
      - DEMYX_WP_USERNAME=demyx
      - TZ=America/Los_Angeles
    hostname: demyx-wp
    image: demyx/code-server:wp
    labels:
      - "traefik.enable=true"
      - "traefik.http.middlewares.demyx-wp-prefix.stripprefix.prefixes=/demyx/cs/"
      - "traefik.http.routers.demyx-wp.entrypoints=https"
      - "traefik.http.routers.demyx-wp.middlewares=demyx-wp-prefix"
      - "traefik.http.routers.demyx-wp.priority=99"
      - "traefik.http.routers.demyx-wp.rule=Host(`domain.tld`) && PathPrefix(`/demyx/cs/`)" # code-server https://domain.tld/demyx/cs/
      - "traefik.http.routers.demyx-wp.service=demyx-wp-port"
      - "traefik.http.routers.demyx-wp.tls.certresolver=demyx"
      - "traefik.http.services.demyx-wp-port.loadbalancer.server.port=8080"
    networks:
      - demyx
    restart: unless-stopped
    volumes:
      - demyx_code:/home/demyx
      - demyx_custom:/etc/demyx/custom
      - demyx_log:/var/log/demyx
      - demyx_wp:/demyx
volumes:
  demyx_code:
    name: demyx_code
  demyx_custom:
    name: demyx_custom
  demyx_db:
    name: demyx_db
  demyx_log:
    name: demyx_log
  demyx_traefik:
    name: demyx_traefik
  demyx_wp:
    name: demyx_wp
