#!/usr/bin/with-contenv bash
# Demyx
# https://demyx.sh

if [[ -n "$CODER_BASE_PATH" ]]; then
    CODER_BASE_PATH="$CODER_BASE_PATH"/cs
fi

su -c "code-server /var/www/html --user-data-dir=/home/www-data/.code/data --extensions-dir=/home/www-data/.code/extensions --disable-telemetry --base-path=$CODER_BASE_PATH" -s /bin/sh www-data
