#!/usr/bin/with-contenv bash
# Demyx
# https://demyx.sh

# Define default variables
[[ -z "$CODER_BS_FILES" ]] && CODER_BS_FILES="[\"/var/www/html/wp-content/themes/**/*\", \"/var/www/html/wp-content/plugins/**/*\"]"
[[ -z "$CODER_BS_PROXY" ]] && CODER_BS_PROXY=localhost
[[ -z "$CODER_BS_DOMAIN" ]] && CODER_BS_DOMAIN=domain.tld
[[ -z "$CODER_BASE_PATH" ]] && CODER_BASE_PATH=/

echo '
// AUTO GENERATED
module.exports={
    ui: false,
    open: false,
    files: '$CODER_BS_FILES',
    proxy: '\"$CODER_BS_PROXY\"',
    rewriteRules:[{
        match: /'$CODER_BS_DOMAIN'/g,
        fn: function (e,r,t) {
            return '\"${CODER_BS_DOMAIN}${CODER_BASE_PATH}/bs\"'
        }
    }],
    scriptPath: function (path) {
        return '\"${CODER_BASE_PATH}/bs\"' + path;
    },
    socket: {
        domain: '\"$CODER_BS_DOMAIN\"'
    }
};' > /tmp/bs.js

[[ "$CODER_BS_FILES" = off ]] && sed -i 's|files:|//files:|g' /tmp/bs.js

browser-sync start --config=/tmp/bs.js
