#!/usr/bin/with-contenv bash
# Demyx
# https://demyx.sh

# Define default variables
CODER_BS_FILES='["/var/www/html/wp-content/themes/**/*", "/var/www/html/wp-content/plugins/**/*"]'
CODER_BS_PROXY=localhost
CODER_BS_DOMAIN="$CODER_DOMAIN"

# Demyx
if [[ -n "$DEMYX_APP_WP_CONTAINER" ]]; then
    CODER_BS_FILES="$DEMYX_BS_FILES"
    CODER_BS_PROXY="$DEMYX_APP_WP_CONTAINER"
    CODER_BS_DOMAIN="$DEMYX_APP_DOMAIN"
fi

echo '
// AUTO GENERATED
module.exports={
    ui: false,
    open: false,
    files: '"$CODER_BS_FILES"',
    proxy: '\"$CODER_BS_PROXY\"',
    rewriteRules:[{
        match: /'$CODER_BS_DOMAIN'/g,
        fn: function (e,r,t) {
            return '\"$CODER_BS_DOMAIN/demyx-bs\"'
        }
    }],
    scriptPath: function (path) {
        return "/demyx-bs" + path;
    },
    socket: {
        domain: '\"$CODER_BS_DOMAIN\"'
    }
};' > /tmp/bs.js
